USE [master]
GO
/****** Object:  Database [RegistroEstudiantes]    Script Date: 22/10/2025 4:11:24 p. m. ******/
CREATE DATABASE [RegistroEstudiantes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RegistroEstudiantes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RegistroEstudiantes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RegistroEstudiantes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RegistroEstudiantes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RegistroEstudiantes] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RegistroEstudiantes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RegistroEstudiantes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET ARITHABORT OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RegistroEstudiantes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RegistroEstudiantes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RegistroEstudiantes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RegistroEstudiantes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET RECOVERY FULL 
GO
ALTER DATABASE [RegistroEstudiantes] SET  MULTI_USER 
GO
ALTER DATABASE [RegistroEstudiantes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RegistroEstudiantes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RegistroEstudiantes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RegistroEstudiantes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RegistroEstudiantes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RegistroEstudiantes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RegistroEstudiantes', N'ON'
GO
ALTER DATABASE [RegistroEstudiantes] SET QUERY_STORE = ON
GO
ALTER DATABASE [RegistroEstudiantes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RegistroEstudiantes]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 22/10/2025 4:11:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Apellido] [nvarchar](100) NOT NULL,
	[Documento] [nvarchar](100) NOT NULL,
	[Correo] [nvarchar](100) NOT NULL,
	[EstudiantePassword] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Correo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Materia]    Script Date: 22/10/2025 4:11:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Creditos] [int] NOT NULL,
	[Descripcion] [nvarchar](300) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MateriasProfesor]    Script Date: 22/10/2025 4:11:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MateriasProfesor](
	[MateriaProfesorID] [int] IDENTITY(1,1) NOT NULL,
	[ProfesorID] [int] NOT NULL,
	[MateriaID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MateriaProfesorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesor]    Script Date: 22/10/2025 4:11:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegistroEstudiantesMaterias]    Script Date: 22/10/2025 4:11:24 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegistroEstudiantesMaterias](
	[RegistroID] [int] IDENTITY(1,1) NOT NULL,
	[EstudianteID] [int] NOT NULL,
	[MateriaID] [int] NOT NULL,
	[ProfesorID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RegistroID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MateriasProfesor]  WITH CHECK ADD FOREIGN KEY([MateriaID])
REFERENCES [dbo].[Materia] ([Id])
GO
ALTER TABLE [dbo].[MateriasProfesor]  WITH CHECK ADD FOREIGN KEY([ProfesorID])
REFERENCES [dbo].[Profesor] ([Id])
GO
ALTER TABLE [dbo].[RegistroEstudiantesMaterias]  WITH CHECK ADD FOREIGN KEY([EstudianteID])
REFERENCES [dbo].[Estudiante] ([Id])
GO
ALTER TABLE [dbo].[RegistroEstudiantesMaterias]  WITH CHECK ADD FOREIGN KEY([MateriaID])
REFERENCES [dbo].[Materia] ([Id])
GO
ALTER TABLE [dbo].[RegistroEstudiantesMaterias]  WITH CHECK ADD FOREIGN KEY([ProfesorID])
REFERENCES [dbo].[Profesor] ([Id])
GO
ALTER TABLE [dbo].[Materia]  WITH CHECK ADD CHECK  (([Creditos]=(3)))
GO
USE [master]
GO
ALTER DATABASE [RegistroEstudiantes] SET  READ_WRITE 
GO
